[package]
name = "timeless"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.9.0-rc0"
num-traits = "0.2"
collider = "0.3.1"
rand = "0.8"